### PR TITLE
Fix bad path for addCSS

### PR DESCRIPTION
**Pull request by Alex-D**
New PR to dev branch

See #4 for details.

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your contribution, maybe you have not noticed commit norms : http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message

Best regards

**Comment by Alex-D** [comment]
Sorry, but there is no CONTRIBUTE file in the repository, so I don't see that :/

**Comment by jeromenadaud** [comment]
Hi,

All contributors are listed in CONTRIBUTORS.md, if it's your first contribution, your name will appear in next release.

Best regards.

**Comment by Alex-D** [comment]
Sorry, I wanted to talk about CONTRIBUTING.md not CONTRIBUTE. But OK, I have read the dev doc for next times :)

**Comment by jeromenadaud** [comment]
Thank you @Alex-D 
Keep contributing !

**Pull request merged**
